
var places = [
    {
        name: "Skyline Walkway Trail",
        lat: -41.273177,
        lng: 174.7573989,
        drive: 800,
        kilo: 20,
        information: "A 12 kilometre walk that takes up to 5 hours, but can be completed in stages.",
        image: "images/skylineWalkway.jpeg"

    },
    {
        name: "Wind Turbine Walk",
        lat: -41.273177,
        lng: 174.7573989,
        drive: 25,
        length: 1,
        information: "Meridian owns and manages the Brooklyn wind turbine, which set international production records for its size.The Electricity Corporation of New Zealand installed the original Brooklyn wind turbine in March 1993. It was part of a research project to find out how wind turbines perform in New Zealand conditions.In winds of between 50km/hour and 80km/hour, the turbine would generate up to 225kW of electricity. The wind turbine generated enough electricity each year for about 110 average New Zealand homes. Power generated by the turbine was fed into the local energy network for general distribution in Wellington.",
        image: "images/windTurpine.jpeg"

    },
    {
        name: "Otari - Wilton's Bush",
        lat: -41.2734203,
        lng: 174.7568516,
        drive: 14,
        kilo: 3,
        information: "Otari Native Botanic Garden and Wilton's Bush Reserve is the only public botanic garden in New Zealand dedicated solely to native plants.",
        image: "images/skylineWalkway.jpeg"

    },
    {
        name: "Town Belt",
        lat: -41.271385,
        lng: 174.7726792,
        drive: 8,
        kilo: 45,
        information: "Today the Town Belt includes 520 hectares, stretching in a horseshoe shape from Mount Victoria (Matairangi) in the north-east, to Berhampore at its southern end, then north-west to Te Ahumairangi Hill between Wadestown and Thorndon.",
        image: "images/townBelt.jpeg"

    },
    {
        name: "Mount Victoria Lookout",
        lat: -41.271385,
        lng: 174.7726792,
        drive: 10,
        kilo: 2,
        information: "Rising 196m above the city, the Mount Victoria Lookout is a Wellington must-do. Head to the lookout and be rewarded with stunning panoramic views of Wellington city and harbour, and beyond.",
        image: "images/mountVic.jpeg"

    },
    {
        name: "Makara Walkway",
        lat: -41.2465409,
        lng: 174.7775244,
        drive: 37,
        kilo: 10,
        information: "The track climbs to vantage points with spectacular views, and returning along the beach.The high cliffs and spectacular views for centuries have provided the people of the area with good vantage points for the defence of their land. A Ngati Ira pa site lies on the promontory at the western end of Fisherman's Bay, and gun emplacements at the top of the cliffs mark the position of Fort Opau, which was garrisoned by 100 soldiers during World War II.",
        image: "images/makara.jpeg"

    },
    {
        name: "Red Rocks",
        lat: -41.3013011,
        lng: 174.8252678,
        drive: 30,
        kilo: 8,
        information: "This unusual rock formation was created when an outcrop of ancient volcanic pillow lava was embedded in younger greywacke, along with red and green siltstone. The Red Rocks Scientific Reserve was created in 1972 after growing public concern about quarrying in the area. On Sundays, the gate is closed and the route is only open for walkers and mountain bikers.",
        image: "images/redRock.jpeg"

    },
    {
        name: "Johnston Hill Reserve",
        lat: -41.3013011,
        lng: 174.8252678,
        drive: 9,
        kilo: 2,
        information: "Johnston Hill Scenic Reserve, in Karori, is at the southern end of Te Wharangi ridge which links Johnston Hill, Kilmister Tops and Mt Kaukau. The bush remnants on Johnston Hill and nearby Otari-Wilton’s Bush are part of a significant native ecosystem: - the native forest that extends from here all the way to Khandallah and Johnsonville Parks. The walk from the lookout to the top of Johnston Hill takes about half an hour. Views from the summit include Wellington Harbour, the Hawkins Hill ridgeline, the Makara hills and the South Island. A track from the summit leads to the Skyline Walkway. Halfway up the hill, side tracks lead to Karori Cemetery and Otari-Wilton’s Bush.",
        image: "images/johnstonHill.jpeg"

    },
    {
        name: "Pohill Reserve",
        lat: -41.3013011,
        lng: 174.8314476,
        drive: 11,
        kilo: 5,
        information: "Visit a ring of four anti-aircraft gun emplacements which were installed during WWII. The surviving octagonal buildings are over 12.5m wide and set on 1.5m deep foundations that contain wings which provided shelter and ammunition niches for the military personnel working with the guns. It's a 10-minute walk to the gun emplacements if you take the track from Ashton Fitchett Drive towards Zealandia's fence, and then double back along the ridge to the site.",
        image: "images/polhill.jpeg"

    },
    {
        name: "Mount Kaukau Summit Hike",
        lat: -41.3013011,
        lng: 174.8314476,
        drive: 20,
        kilo: 4,
        information: "A 4.2 kilometre walk, taking about 3 hours to complete.",
        image: "images/mtKaukau.jpeg"

    },

    

     
]


$('#map').hide();

$(document).ready(function(){
  $('#details').click(function(){
    $('#map').show();
    var distance = document.getElementById('distance').value;
    var duration = document.getElementById('duration').value;
    console.log(distance,duration);
    initMap(distance,duration);
  });


});

$("#startDate").datepicker({
    dateFormat : "dd-mm-yy",
    changeMonth : true,
    minDate : new Date(),
    maxDate : '+1y',
    onSelect : function(date){
        var selectDate = new Date(date);
        var msecsInADay = 86400000;
        var stDate = new Date(selectDate.getTime() + msecsInADay);

        $('#endDate').datepicker('option', 'minDate', stDate);
        var enDate = new Date(selectDate.getTime() + 15 * msecsInADay);

        $('#endDate').datepicker('option', 'maxDate', enDate);

    }
});

$("#endDate").datepicker({
    dateFormat : "dd-mm-yy",
    changeMonth : true,
    
});

function dateDiff(){
    var start = $(startDate).datepicker('getDate');
    var end = $(endDate).datepicker('getDate');
    var days = (end - start)/1000/60/60/24;
}



// API Key - could be sourced from anywhere
// var API_KEY = 'AIzaSyDbpUzFX_ey574BjAKWiBA7VHN11-27IHc';

// Create script tag
var script = document.createElement('script');
// The API key needs to be part of the source
script.src = "https://maps.googleapis.com/maps/api/js?key=" + API_KEY 

// Add the script tag to the page (this makes the browser download the script)
document.body.appendChild(script);


// This function is called once Google Maps has finished loading
function initMap(distance,duration) {
    
//   // Create map centered at wellington
  var oldwindow;
  var center;
   //center coordinates
   if (duration === "10") {
    center = {lat: -41.2911449, lng: 174.7814447};

} else if (duration === "30"){
    center = {lat:-41.273177 , lng:174.7573989};
  };

  console.log(center);
var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 13, center: center});


  
  


// // loop through all the objects in the array locations
for ( var i = 0; i<places.length; i++){
    console.log(distance,typeof(distance), duration, typeof(duration));
    console.log(places[i].kilo, typeof(places[i].kilo));
    console.log(places[i].drive, typeof(places[i].drive));
    console.log(places[i].kilo <= distance);
    console.log(places[i].drive <= duration);

    if (places[i].kilo <= distance && places[i].drive <= duration){
    //create content dynamically
    var content = '<div class="bg-primary h4" id="' + places[i].information + '">' +
    '<h5> '+ places[i].name + '</h5>' +
    '<h6>'+ places[i].kilo + '</h6>' +
    '<h6>Distance: '+ places[i].kilo +  '</h6>'+
    '<h6>Duration: '+ places[i].drive + ' min</h6>' +
    '<h6> from the nearest i-site visitor\'s information center</h6>'+
    '</div>';
    var infowindow = new google.maps.InfoWindow({
        content : content
      });

      //position to add marker
      var position = {lat:places[i].lat , lng:places[i].long };

      //crete marker
      var marker = new google.maps.Marker({
        position : position,
        map : map
      });

      newWindow(marker, infowindow);
  
      function newWindow(newMarker, newInfowindow){
   
        newMarker.addListener('click', function(){
          if (oldwindow){
            oldwindow.close();
          }
          newInfowindow.open(map, newMarker);
          oldwindow=newInfowindow;
           
        });//end of addListener
      }//end of newwindow function


     }
    }//end of for

}//end of initMap
